---
title: "Lab 8 - Linear Regression in R"
author: "Renee Albrecht"
date: "November 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Step 1 - Load in tidyverse and read in data

library(tidyverse)
salmon <- read_csv("salmon_imports.csv")


```

```{r}
#Step 2 - Make an exploratory scatterplot 

salmon_plot <- ggplot(salmon, aes(x = year, y = salmon_fresh)) +
  geom_point()

salmon_plot

## Overall, the exploratory scatterplot suggests that the relationship between year and salmon imports is linear. I have some hesitation due to the kinks in the line in 2004-2005 and 2013-2014. 

```

```{r}

#Step 3 - Linear Regression in R

salmon_model <- lm(salmon_fresh ~ year, data = salmon)

salmon_model

#Write out model equation based on findings: 
# Based on y = β0 + β1x + (error term)


#Imports(tons) = -14982940 + 7550(Year)
#Slope means rate at which salmon imports increase per year 
#Y-intercept implies that there will be negative salmon caught in year "0" - this is nonscensical and implies that the model should NOT be used to extrapolate past values 


```

```{r}
#Step 4 - Model diagnostics 


par(mfrow = c(2,2)) #to view all four disgnostic plots at once
plot(salmon_model) #to view model diagnostics

#Do residuals appear normally distributed? 
#Yes, the residuals appear normally distributed 

#Any concerns about heteroscedasticity or outliers? 
#No, the spread of the residuals about the models remains relatively even over 'x'. (Where do I look for outliers?)


```

```{r}
#Step 5 - Explore model fit and significance 

summary(salmon_model) #see detailed model information, including model fit information and statistics

#Does year significantly predict salmon imports? 
#Yes, 95% of variance in salmon imports is predictable by year 

#What does the R-squared value actually mean in words?
#In this model, R-squared tells us the proportion of variance in salmon imports that is explained by the value of the corresponding year. 

#What proportion of the variance in salmon imports is NOT explained by year?
#Approximately 5% of salmon imports is NOT explained by year 


```

```{r}
#Step 6 - Prepare a final graph 

salmon_final_graph <- ggplot(salmon, aes(x = year, y = salmon_fresh)) +
geom_point() +
geom_smooth(method = lm, se = TRUE, size = 0.5, color = "gray20") +
theme_bw() +
scale_x_continuous(expand = c(0,0), limits = c(1990, 2017)) +
labs(x = "Year", y = "U.S. Annual Fresh Salmon Imports\n(1,000 pounds)")

salmon_final_graph

#geom_smooth adds regression line to scatter plot, "se : logical value. If TRUE, confidence interval is displayed around smooth." "


```

```{r}
#Step 7 - Make predictions using the model 

#Option 1 (not recommended): Plug each of those years into the model equation separately to calculate the expected U.S. imports.
#Option 2 (recommended): Create a data frame containing the ‘new values’ that you want to make predictions for, feed that into the predict() function

#Let's do option 2 - create new data frame called 'new_years'

new_years <- data.frame(year = c(2022, 2024, 2026, 2028))
new_years

#Next, feed data fram into predict() function, letting it know which model to use to make predictions for new values 

#Include 'interval = "confidence"' to also report the lower and upper bounds of the 95% CI for model fit at each year 

future_predict <- predict(salmon_model, new_data = new_years, interval = "confidence")
future_predict

predictions <- data.frame(new_years, future_predict)
predictions




```


```{r}
#Step 8 - Find Pearson's r (correlation)

salmon_pr <- cor.test(salmon$year, salmon$salmon_fresh)
salmon_pr

# Based on the Pearson's R (0.973587), I would describe this as a strong positive correlation. 

```

```{r}
#Step 9 - Write a concluding statement about the relationship 

#“Year significantly predicts salmon imports (b = 0.79, t(26) = 21.723, p < 0.001) with a strong positive correlation between the two (Pearson’s r = 0.97). The overall model (Imports(tons) = -14982940 + 7550(Year)?) explains a significant amount of variance in sepal width (F(1,26) = 471.9, p < 0.001, R2 = 0.95).”


```






